name: Continuous Deployment Docker

on:
  push:
    branches: [ "main" ]
    paths:
      - 'DockerizedService/**'
      - 'DockerizedService/Dockerfile'
      - '.github/workflows/DockerizedService.yaml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push the docker image
        uses: docker/build-push-action@v4
        with:
          context: ./DockerizedService
          file: ./DockerizedService/Dockerfile
          push: true
          tags: oreakinodidi/dockerizedservice:${{ github.sha }}